# Build worker image (VM template)
image: Visual Studio 2015

version: '{build}'

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: false

# build Configuration, i.e. Debug, Release, etc.
configuration: Debug

install:
  - cinst python -version 2.7.6
  - cmd: pip install sphinx sphinx-autobuild sphinx_rtd_theme

build_script:
  - cmd: make.bat teamcity

skip_tags: true

# build cache to preserve files/folders between builds
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

artifacts:
  - path: artifacts
  - path: docs\build\html
    name: docs