//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitDepend.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitDepend.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The build script failed.
        /// </summary>
        internal static string RET_BUILD_SCRIPT_FAILED {
            get {
                return ResourceManager.GetString("RET_BUILD_SCRIPT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the nuget cache directory.
        /// </summary>
        internal static string RET_CREATE_CACHE_DIR_FAILED {
            get {
                return ResourceManager.GetString("RET_CREATE_CACHE_DIR_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The packages in packages.config due not match currently built packages..
        /// </summary>
        internal static string RET_DEPENDENCY_PACKAGES_MISTMATCH {
            get {
                return ResourceManager.GetString("RET_DEPENDENCY_PACKAGES_MISTMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency packages need to be built..
        /// </summary>
        internal static string RET_DEPENDENCY_PACKAGES_NOT_BUILT {
            get {
                return ResourceManager.GetString("RET_DEPENDENCY_PACKAGES_NOT_BUILT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exist.
        /// </summary>
        internal static string RET_DIRECTORY_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("RET_DIRECTORY_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to execute the git command.
        /// </summary>
        internal static string RET_GIT_COMMAND_FAILED {
            get {
                return ResourceManager.GetString("RET_GIT_COMMAND_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a git repository.
        /// </summary>
        internal static string RET_GIT_REPO_NOT_FOUND {
            get {
                return ResourceManager.GetString("RET_GIT_REPO_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Arguments.
        /// </summary>
        internal static string RET_INVALID_ARGS {
            get {
                return ResourceManager.GetString("RET_INVALID_ARGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid branch checked out.
        /// </summary>
        internal static string RET_INVALID_BRANCH_CHECKED_OUT {
            get {
                return ResourceManager.GetString("RET_INVALID_BRANCH_CHECKED_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Command.
        /// </summary>
        internal static string RET_INVALID_COMMAND {
            get {
                return ResourceManager.GetString("RET_INVALID_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Uri format.
        /// </summary>
        internal static string RET_INVALID_URI_FORMAT {
            get {
                return ResourceManager.GetString("RET_INVALID_URI_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Dependency.
        /// </summary>
        internal static string RET_MISSING_DEPENDENCY {
            get {
                return ResourceManager.GetString("RET_MISSING_DEPENDENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to execute a nuget command.
        /// </summary>
        internal static string RET_NUGET_COMMAND_FAILED {
            get {
                return ResourceManager.GetString("RET_NUGET_COMMAND_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string RET_SUCCESS {
            get {
                return ResourceManager.GetString("RET_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        internal static string RET_UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("RET_UNKNOWN_ERROR", resourceCulture);
            }
        }
    }
}
