//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitDepend.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitDepend.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking out the {0} branch on {1}.
        /// </summary>
        internal static string CHECKING_OUT_BRANCH_ON_REPONAME {
            get {
                return ResourceManager.GetString("CHECKING_OUT_BRANCH_ON_REPONAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully cloned all dependencies.
        /// </summary>
        internal static string CLONED_ALL_DEPS {
            get {
                return ResourceManager.GetString("CLONED_ALL_DEPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloning {0} into {1}.
        /// </summary>
        internal static string CLONING_DEP_INTO_DIRECTORY {
            get {
                return ResourceManager.GetString("CLONING_DEP_INTO_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config updated successfully.
        /// </summary>
        internal static string CONFIG_UPDATED {
            get {
                return ResourceManager.GetString("CONFIG_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the {0} branch on {1}.
        /// </summary>
        internal static string CREATING_BRANCH_ON_REPONAME {
            get {
                return ResourceManager.GetString("CREATING_BRANCH_ON_REPONAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dependency:.
        /// </summary>
        internal static string DEPENDENCY {
            get {
                return ResourceManager.GetString("DEPENDENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency with dir {0} has been added successfully..
        /// </summary>
        internal static string DEPENDENCY_ADDED_SUCCESFULLY {
            get {
                return ResourceManager.GetString("DEPENDENCY_ADDED_SUCCESFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}- Dependency in directory: {1} is missing a name, or config file.&quot;.
        /// </summary>
        internal static string DEPENDENCY_MISSING_NAME {
            get {
                return ResourceManager.GetString("DEPENDENCY_MISSING_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All dependencies on the correct branch.
        /// </summary>
        internal static string DEPS_CORRECT_BRANCH {
            get {
                return ResourceManager.GetString("DEPS_CORRECT_BRANCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     dir: .
        /// </summary>
        internal static string DIRECTORY {
            get {
                return ResourceManager.GetString("DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate {0}.
        /// </summary>
        internal static string DIRECTORY_NOT_FOUND {
            get {
                return ResourceManager.GetString("DIRECTORY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     expected {0} but was {1}.
        /// </summary>
        internal static string EXPECTED_BRANCH_BUT_WAS_BRANCH {
            get {
                return ResourceManager.GetString("EXPECTED_BRANCH_BUT_WAS_BRANCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Give up. I&apos;ll figure it out myself..
        /// </summary>
        internal static string GIVE_UP_OPTION {
            get {
                return ResourceManager.GetString("GIVE_UP_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Branch!.
        /// </summary>
        internal static string INVALID_BRANCH {
            get {
                return ResourceManager.GetString("INVALID_BRANCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to everything looks good..
        /// </summary>
        internal static string LOOKS_GOOD {
            get {
                return ResourceManager.GetString("LOOKS_GOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Making update commit on .
        /// </summary>
        internal static string MAKING_UPDATE_COMMIT_ON {
            get {
                return ResourceManager.GetString("MAKING_UPDATE_COMMIT_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     name: .
        /// </summary>
        internal static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all dependencies are on the correct branch..
        /// </summary>
        internal static string NOT_ALL_DEPS_CORRECT_BRANCH {
            get {
                return ResourceManager.GetString("NOT_ALL_DEPS_CORRECT_BRANCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nothing was updated.
        /// </summary>
        internal static string NOTHING_UPDATED {
            get {
                return ResourceManager.GetString("NOTHING_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All packages are up to date.
        /// </summary>
        internal static string PACKAGES_UP_TO_DATE {
            get {
                return ResourceManager.GetString("PACKAGES_UP_TO_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to project:.
        /// </summary>
        internal static string PROJECT {
            get {
                return ResourceManager.GetString("PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified artifacts directory could not be found.
        /// </summary>
        internal static string RET_ARTIFACTS_DIR_NOT_FOUND {
            get {
                return ResourceManager.GetString("RET_ARTIFACTS_DIR_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The build script failed.
        /// </summary>
        internal static string RET_BUILD_SCRIPT_FAILED {
            get {
                return ResourceManager.GetString("RET_BUILD_SCRIPT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the nuget cache directory.
        /// </summary>
        internal static string RET_CREATE_CACHE_DIR_FAILED {
            get {
                return ResourceManager.GetString("RET_CREATE_CACHE_DIR_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitDepend.json file not found.
        /// </summary>
        internal static string RET_DEPEND_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("RET_DEPEND_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exist.
        /// </summary>
        internal static string RET_DIRECTORY_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("RET_DIRECTORY_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to execute the git command.
        /// </summary>
        internal static string RET_GIT_COMMAND_FAILED {
            get {
                return ResourceManager.GetString("RET_GIT_COMMAND_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a git repository.
        /// </summary>
        internal static string RET_GIT_REPO_NOT_FOUND {
            get {
                return ResourceManager.GetString("RET_GIT_REPO_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Arguments.
        /// </summary>
        internal static string RET_INVALID_ARGS {
            get {
                return ResourceManager.GetString("RET_INVALID_ARGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid branch checked out.
        /// </summary>
        internal static string RET_INVALID_BRANCH_CHECKED_OUT {
            get {
                return ResourceManager.GetString("RET_INVALID_BRANCH_CHECKED_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Command.
        /// </summary>
        internal static string RET_INVALID_COMMAND {
            get {
                return ResourceManager.GetString("RET_INVALID_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Uri format.
        /// </summary>
        internal static string RET_INVALID_URI_FORMAT {
            get {
                return ResourceManager.GetString("RET_INVALID_URI_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Dependency.
        /// </summary>
        internal static string RET_MISSING_DEPENDENCY {
            get {
                return ResourceManager.GetString("RET_MISSING_DEPENDENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named dependency did not match.
        /// </summary>
        internal static string RET_NAME_DID_NOT_MATCH {
            get {
                return ResourceManager.GetString("RET_NAME_DID_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to execute a nuget command.
        /// </summary>
        internal static string RET_NUGET_COMMAND_FAILED {
            get {
                return ResourceManager.GetString("RET_NUGET_COMMAND_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string RET_SUCCESS {
            get {
                return ResourceManager.GetString("RET_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        internal static string RET_UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("RET_UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created the {0} branch in all repositories..
        /// </summary>
        internal static string SUCCESFULLY_CREATED_BRANCH_ALL_REPOS {
            get {
                return ResourceManager.GetString("SUCCESFULLY_CREATED_BRANCH_ALL_REPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted the {0} branch in all repositories..
        /// </summary>
        internal static string SUCCESFULLY_DELETED_BRANCH_ALL_REPOS {
            get {
                return ResourceManager.GetString("SUCCESFULLY_DELETED_BRANCH_ALL_REPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Switch branch to .
        /// </summary>
        internal static string SWITCH_BRANCH_OPTION {
            get {
                return ResourceManager.GetString("SWITCH_BRANCH_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all dependency branches synchronized successfully!.
        /// </summary>
        internal static string SYNC_SUCCESS {
            get {
                return ResourceManager.GetString("SYNC_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huh? Try again..
        /// </summary>
        internal static string TRY_AGAIN {
            get {
                return ResourceManager.GetString("TRY_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update complete!.
        /// </summary>
        internal static string UPDATE_COMPLETE {
            get {
                return ResourceManager.GetString("UPDATE_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Update config to point to .
        /// </summary>
        internal static string UPDATE_CONFIG {
            get {
                return ResourceManager.GetString("UPDATE_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated packages: .
        /// </summary>
        internal static string UPDATED_PACKAGES {
            get {
                return ResourceManager.GetString("UPDATED_PACKAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using {0} for {1}.
        /// </summary>
        internal static string USING_BRANCH_FOR_CONFIG {
            get {
                return ResourceManager.GetString("USING_BRANCH_FOR_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying the checked out branch.
        /// </summary>
        internal static string VERIFYING_CHECKED_OUT_BRANCH {
            get {
                return ResourceManager.GetString("VERIFYING_CHECKED_OUT_BRANCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What should I do?.
        /// </summary>
        internal static string WHAT_SHOULD_I_DO {
            get {
                return ResourceManager.GetString("WHAT_SHOULD_I_DO", resourceCulture);
            }
        }
    }
}
